let riasecQuestions = [
    { proposition_id: 1, groupe_id: 1, personnalite_id: 1, intitule: "Vous aimez avoir des activités à l’extérieur, travailler en plein air" },
    { proposition_id: 2, groupe_id: 1, personnalite_id: 2, intitule: "Vous aimez élargir vos connaissances par l’étude, pouvoir approfondir un sujet" },
    { proposition_id: 3, groupe_id: 1, personnalite_id: 3, intitule: "Vous aimez travailler de façon indépendante, sans méthode ni objectif structurés" },
    { proposition_id: 4, groupe_id: 1, personnalite_id: 4, intitule: "Vous aimez travailler avec d’autres personnes pour les informer" },
    { proposition_id: 5, groupe_id: 1, personnalite_id: 5, intitule: "Vous admirez les personnes qui ont du pouvoir ou gagnent beaucoup d’argent" },
    { proposition_id: 6, groupe_id: 1, personnalite_id: 6, intitule: "Vous aimez travailler avec des chiffres" },
    { proposition_id: 7, groupe_id: 2, personnalite_id: 4, intitule: "Vous admirez les personnes qui travaillent pour soigner les autres" },
    { proposition_id: 8, groupe_id: 2, personnalite_id: 6, intitule: "Vous aimez une organisation claire et bien définie" },
    { proposition_id: 9, groupe_id: 2, personnalite_id: 5, intitule: "Vous aimez contribuer à atteindre les objectifs d’une organisation" },
    { proposition_id: 10, groupe_id: 2, personnalite_id: 1, intitule: "Vous aimez le sport, vous dépenser physiquement" },
    { proposition_id: 11, groupe_id: 2, personnalite_id: 2, intitule: "Vous aimez étudier les choses, les phénomènes ou les comportements" },
    { proposition_id: 12, groupe_id: 2, personnalite_id: 3, intitule: "Vous admirez les personnes qui ont des capacités artistiques" },
    { proposition_id: 13, groupe_id: 3, personnalite_id: 4, intitule: "Vous aimez travailler avec d’autres personnes pour les former, les entraîner" },
    { proposition_id: 14, groupe_id: 3, personnalite_id: 3, intitule: "Vous aimez les changements ou les situations imprévues" },
    { proposition_id: 15, groupe_id: 3, personnalite_id: 6, intitule: "Vous aimez ne faire qu’une seule chose à la fois et vous ne vous laissez pas distraire" },
    { proposition_id: 16, groupe_id: 3, personnalite_id: 5, intitule: "Vous aimez donner des ordres ou consignes et organiser l’activité des autres" },
    { proposition_id: 17, groupe_id: 3, personnalite_id: 2, intitule: "Vous aimez tirer vos propres conclusions de l’analyse d’une situation donnée" },
    { proposition_id: 18, groupe_id: 3, personnalite_id: 1, intitule: "Vous aimez conduire des véhicules ou faire fonctionner des machines" },
    { proposition_id: 19, groupe_id: 4, personnalite_id: 1, intitule: "Vous aimez fabriquer ou réparer des objets" },
    { proposition_id: 20, groupe_id: 4, personnalite_id: 3, intitule: "Vous aimez ne pas savoir précisément ce que vous avez à faire" },
    { proposition_id: 21, groupe_id: 4, personnalite_id: 6, intitule: "Vous aimez mettre en œuvre des « bonnes pratiques » acquises par l’expérience" },
    { proposition_id: 22, groupe_id: 4, personnalite_id: 5, intitule: "Vous aimez faire preuve d’initiative et prendre des décisions rapides" },
    { proposition_id: 23, groupe_id: 4, personnalite_id: 4, intitule: "Vous aimez écouter, dialoguer, essayer de comprendre les autres" },
    { proposition_id: 24, groupe_id: 4, personnalite_id: 2, intitule: "Vous aimez vous fier à votre jugement pour décider comment faire les choses" },
    { proposition_id: 25, groupe_id: 5, personnalite_id: 3, intitule: "Vous aimez faire plusieurs activités en même temps, ou passer d’une action à l’autre" },
    { proposition_id: 26, groupe_id: 5, personnalite_id: 5, intitule: "Vous aimez décider de ce qui doit être fait" },
    { proposition_id: 27, groupe_id: 5, personnalite_id: 4, intitule: "Vous aimez rencontrer des gens nouveaux" },
    { proposition_id: 28, groupe_id: 5, personnalite_id: 2, intitule: "Vous aimez vérifier une conclusion par des tests ou des informations complémentaires" },
    { proposition_id: 29, groupe_id: 5, personnalite_id: 6, intitule: "Vous aimez appuyer vos conclusions sur des bases déjà prouvées" },
    { proposition_id: 30, groupe_id: 5, personnalite_id: 1, intitule: "Vous aimez bricoler, utiliser des outils tels que tournevis, ciseaux, pinces, etc.…" },
    { proposition_id: 31, groupe_id: 6, personnalite_id: 2, intitule: "Vous aimez résoudre les problèmes de façon rationnelle, étape par étape" },
    { proposition_id: 32, groupe_id: 6, personnalite_id: 1, intitule: "Vous aimez la nature, les plantes, les animaux…" },
    { proposition_id: 33, groupe_id: 6, personnalite_id: 6, intitule: "Vous aimez respecter les valeurs que vous vous êtes fixées" },
    { proposition_id: 34, groupe_id: 6, personnalite_id: 4, intitule: "Vous aimez faire un travail en commun avec d’autres" },
    { proposition_id: 35, groupe_id: 6, personnalite_id: 5, intitule: "Vous aimez relever des défis" },
    { proposition_id: 36, groupe_id: 6, personnalite_id: 3, intitule: "Vous aimez vous fier à votre intuition pour prendre des décisions" },
    { proposition_id: 37, groupe_id: 7, personnalite_id: 5, intitule: "Vous aimez convaincre les autres d’agir d’une certaine façon" },
    { proposition_id: 38, groupe_id: 7, personnalite_id: 3, intitule: "Vous aimez résoudre un problème sans avoir recours à une méthode logique" },
    { proposition_id: 39, groupe_id: 7, personnalite_id: 2, intitule: "Vous aimez prendre une décision après une réflexion, si possible logique" },
    { proposition_id: 40, groupe_id: 7, personnalite_id: 6, intitule: "Vous aimez suivre attentivement un plan pour atteindre le meilleur résultat possible" },
    { proposition_id: 41, groupe_id: 7, personnalite_id: 4, intitule: "Vous aimez écouter les autres et les conseiller sur la façon de résoudre leurs problèmes" },
    { proposition_id: 42, groupe_id: 7, personnalite_id: 1, intitule: "Vous aimez trouver une solution concrète, réaliste et simple aux problèmes" },
    { proposition_id: 43, groupe_id: 8, personnalite_id: 2, intitule: "Vous aimez concevoir ou améliorer les méthodes de travail" },
    { proposition_id: 44, groupe_id: 8, personnalite_id: 1, intitule: "Vous aimez utiliser votre « bon sens »" },
    { proposition_id: 45, groupe_id: 8, personnalite_id: 4, intitule: "Vous aimez rendre service, venir en aide à d’autres personnes" },
    { proposition_id: 46, groupe_id: 8, personnalite_id: 5, intitule: "Vous aimez répondre aux objections de vos interlocuteurs pour mieux les convaincre" },
    { proposition_id: 47, groupe_id: 8, personnalite_id: 3, intitule: "Vous aimez montrer votre originalité" },
    { proposition_id: 48, groupe_id: 8, personnalite_id: 6, intitule: "Vous aimez travailler avec soin pour obtenir un résultat parfait" },
    { proposition_id: 49, groupe_id: 9, personnalite_id: 4, intitule: "Vous aimez ou aimeriez animer des activités collectives, associatives…" },
    { proposition_id: 50, groupe_id: 9, personnalite_id: 2, intitule: "Vous aimez ou aimeriez étudier la physique, la biologie, ou la technologie" },
    { proposition_id: 51, groupe_id: 9, personnalite_id: 1, intitule: "Vous aimez démonter un appareil pour le réparer vous-même" },
    { proposition_id: 52, groupe_id: 9, personnalite_id: 5, intitule: "Vous aimez discuter avec un commerçant pour obtenir des réductions de prix" },
    { proposition_id: 53, groupe_id: 9, personnalite_id: 3, intitule: "Vous aimez exprimer vos idées, vos points de vue ou vos émotions" },
    { proposition_id: 54, groupe_id: 9, personnalite_id: 6, intitule: "Vous aimez rédiger un résumé, une lettre, un compte-rendu" },
    { proposition_id: 55, groupe_id: 10, personnalite_id: 5, intitule: "Vous aimez faire face aux situations urgentes ou imprévues" },
    { proposition_id: 56, groupe_id: 10, personnalite_id: 6, intitule: "Vous aimez vous occuper de démarches administratives ou d’ordre juridique" },
    { proposition_id: 57, groupe_id: 10, personnalite_id: 4, intitule: "Vous aimez ou aimeriez faire des reportages, écrire des articles, etc…" },
    { proposition_id: 58, groupe_id: 10, personnalite_id: 2, intitule: "Vous aimez chercher à comprendre et à expliquer le pourquoi des choses et des êtres" },
    { proposition_id: 59, groupe_id: 10, personnalite_id: 3, intitule: "Vous aimez imaginer des solutions qui sortent de l’ordinaire" },
    { proposition_id: 60, groupe_id: 10, personnalite_id: 1, intitule: "Vous aimez ou aimeriez utiliser un objet que vous avez fabriqué vous-même" },
    { proposition_id: 61, groupe_id: 11, personnalite_id: 4, intitule: "Vous aimez apprendre aux autres ce que vous savez" },
    { proposition_id: 62, groupe_id: 11, personnalite_id: 1, intitule: "Vous aimez collectionner des choses : timbres, cartes postales, pierres, etc.…" },
    { proposition_id: 63, groupe_id: 11, personnalite_id: 6, intitule: "Vous aimez passer une grande partie de votre temps sur des documents écrits" },
    { proposition_id: 64, groupe_id: 11, personnalite_id: 5, intitule: "Vous aimez ou aimeriez vendre des produits ou services" },
    { proposition_id: 65, groupe_id: 11, personnalite_id: 2, intitule: "Vous aimez vous servir d’un microscope ou autre appareil de mesure…" },
    { proposition_id: 66, groupe_id: 11, personnalite_id: 3, intitule: "Vous aimez ou aimeriez avoir des loisirs créatifs : peinture, musique…" },
    { proposition_id: 67, groupe_id: 12, personnalite_id: 6, intitule: "Vous aimez classer, ordonner des documents ou des objets" },
    { proposition_id: 68, groupe_id: 12, personnalite_id: 5, intitule: "Vous aimez conduire une discussion, un débat" },
    { proposition_id: 69, groupe_id: 12, personnalite_id: 4, intitule: "Vous aimez échanger des idées avec les autres" },
    { proposition_id: 70, groupe_id: 12, personnalite_id: 1, intitule: "Vous aimez que ce que vous faites débouche sur des résultats concrets" },
    { proposition_id: 71, groupe_id: 12, personnalite_id: 2, intitule: "Vous aimez ou aimeriez mettre au point et réaliser des expériences scientifiques" },
    { proposition_id: 72, groupe_id: 12, personnalite_id: 3, intitule: "Vous aimez étudier ou inventer plusieurs solutions pour répondre à un problème" }
]

export default riasecQuestions;
