import riasecQuestions from "../Riasec/data.js";

let DjangoQuestions = [
    { question: "Abuser de la confiance des gens.", code: "H1131" },
    { question: "Accepter les excuses facilement.", code: "H133" },
    { question: "Accepter des tâches difficiles.", code: "H515" },
    { question: "Accepter peu des autres.", code: "H615" },
    { question: "Accepter les faiblesses des autres.", code: "H139" },
    { question: "Accepter les gens tels qu'ils sont.", code: "H106" },
    { question: "Accepter les conséquences de mes actions.", code: "H266" },
    { question: "Accepter la première chose qui vient.", code: "H1384" },
    { question: "Accepter ce que les autres disent.", code: "H962" },
    { question: "Accomplir beaucoup de travail.", code: "H554" },
    { question: "Accomplir mon travail à temps.", code: "H230" },
    { question: "Reconnaître les réalisations des autres.", code: "H152" },
    { question: "Acquérir des compétences rapidement.", code: "H1338" },
    { question: "Agir selon ma conscience.", code: "H178" },
    { question: "Agir selon mes propres sentiments.", code: "H1367" },
    { question: "Agir en tant que leader.", code: "Q176" },
    { question: "Agir comme je le veux.", code: "H795" },
    { question: "Agir comme si j'étais quelqu'un d'autre et m'identifier complètement au rôle.", code: "A18" },
    { question: "Agir comme si j'étais constamment sur scène.", code: "T17" },
    { question: "Agir comme si certaines lois ne s'appliquaient pas à moi.", code: "T19" },
    { question: "Agir aux dépens des autres.", code: "H794" },
    { question: "Agir avant de réfléchir aux conséquences.", code: "V207" },
    { question: "Agir à l'aise avec les autres.", code: "H41" },
    { question: "Agir contre la raison.", code: "H1370" },
    { question: "Agir impulsivement quand quelque chose me dérange.", code: "Q253" },
    { question: "Agir différemment selon les situations.", code: "P342" },
    { question: "Agir comme des personnes plus âgées que moi.", code: "Q27" },
    { question: "Agir comme des personnes plus jeunes que moi.", code: "Q182" },
    { question: "Agir ou se sentir d'une manière qui ne me correspond pas.", code: "A43" },
    { question: "Exprimer mes frustrations sur les autres.", code: "H758" },
    { question: "Agir correctement dans la plupart des situations.", code: "Q53" },
    { question: "Agir rapidement sans réfléchir.", code: "H866" },
    { question: "Agir spontanément sans réfléchir aux conséquences.", code: "A137" },
    { question: "Agir de manière sauvage et folle.", code: "H871" },
    { question: "Me demander si les personnes que je connais sont vraiment dignes de confiance.", code: "T2736" },
    { question: "Me demander qui je suis vraiment.", code: "A52" },
    { question: "Ne serai pas satisfait tant que je n'aurai pas tout ce que je mérite.", code: "P475" },
    { question: "Ne laisserai pas les gens tranquilles.", code: "H768" },
    { question: "Ne laisserai pas les autres me dominer.", code: "Q249" },
    { question: "Ne prendrai pas le blâme pour quelque chose qui n'est pas ma faute.", code: "P431" },
    { question: "Travailler selon une routine.", code: "H264" },
    { question: "Travailler mieux quand je suis seul.", code: "V132" },
    { question: "Travailler dur.", code: "H1206, X44" },
    { question: "Travailler plus dur après un échec.", code: "Q113" },
    { question: "Travailler plus d'heures que la plupart des gens.", code: "Q242" },
    { question: "Travailler sur moi-même pour m'améliorer.", code: "E170" },
    { question: "Extérioriser mes angoisses en faisant quelque chose de constructif ou de créatif.", code: "Q247" },
    { question: "Travailler si dur que ma santé mentale en a souffert.", code: "T2744" },
    { question: "Travailler si dur que mes relations en ont souffert.", code: "T2745" },
    { question: "Travailler trop.", code: "P484" },
    { question: "Travaillais dur à l'école.", code: "Q174" },
    { question: "M'inquiéter beaucoup de contracter une maladie grave.", code: "C1" },
    { question: "M'inquiéter beaucoup en cas de symptôme physique nouveau.", code: "C12" },
    { question: "M'inquiéter d'être embarrassé.", code: "V308" },
    { question: "M'inquiéter pour ma santé.", code: "C5" },
    { question: "M'inquiéter que des gens prennent mes possessions.", code: "M16" },
    { question: "M'inquiéter des choses.", code: "H1157, X5" },
    { question: "M'inquiéter de ce que les gens pensent de moi.", code: "P420" },
    { question: "M'inquiéter tellement que je n'arrive à rien faire.", code: "T2754" },
    { question: "M'inquiéter que certaines personnes profitent injustement de moi.", code: "V250" },
    { question: "M'inquiéter que certaines personnes essaient de me tromper ou de me duper.", code: "V215" },
    { question: "M'inquiéter trop de ce que les autres pourraient penser.", code: "T2757" },
    { question: "Je porterais toujours un casque si je faisais du vélo.", code: "E61" },
    { question: "Je serais effrayé de faire un discours en public.", code: "Q45" },
    { question: "Mes amis et ma famille diraient que je m'intéresse à beaucoup de choses différentes.", code: "W236" },
    { question: "Mes amis diraient que je suis courageux.", code: "W364" },
    { question: "Mes amis diraient que j'ai beaucoup d'énergie positive.", code: "W378" },
    { question: "Je serais bon pour sauver des gens d'un bâtiment en flammes.", code: "Q31" },
    { question: "Je serais plus heureux si je pouvais m'acheter plus de choses.", code: "M76" },
    { question: "Je serais nerveux en jouant le clown devant les autres.", code: "R30" },
    { question: "Je serais contrarié si je voyais un animal blessé.", code: "A46" },
    { question: "Je serais contrarié si mon succès se faisait aux dépens de quelqu'un d'autre.", code: "A127" },
    { question: "Je changerais de nom ou d'histoire pour me sortir d'ennuis.", code: "V244" },
    { question: "Je considérerais l'adoption d'un enfant handicapé.", code: "X153" },
    { question: "Je décrirais mes expériences comme étant un peu ennuyeuses.", code: "X147" },
    { question: "Je me décrirais comme une personne normale.", code: "T2768" },
    { question: "Je ferais n'importe quoi pour avoir une montée d'adrénaline.", code: "T2769" },
    { question: "Je profiterais d'un travail où ma vie est en jeu.", code: "T2771" },
    { question: "J'apprécierais d'être sur un bateau à voile pendant une tempête.", code: "Q115" },
    { question: "J'apprécierais de faire campagne pour un poste politique.", code: "R9" },
    { question: "J'apprécierais de plonger depuis des falaises de grandes hauteurs.", code: "T2775" },
    { question: "J'apprécierais la dangerosité d'être policier ou pompier.", code: "T2776" },
    { question: "J'aurais peur de marcher dans une partie de la ville à forte criminalité.", code: "R52" },
    { question: "Je me sentirais mal à l'aise de profiter des autres.", code: "Q8" },
    { question: "Je me sentirais très mal si je volais à quelqu'un.", code: "D102" },
    { question: "Je trouverais difficile de demander une augmentation de salaire.", code: "S31" },
    { question: "Je trouverais ça pénible de voir quelqu'un dormir dans la rue.", code: "D36" },
    { question: "Je ferais du streaking en public juste pour le frisson.", code: "T2782" },
    { question: "Je détesterais être considéré comme bizarre ou étrange.", code: "D46" },
    { question: "Je vendrais sciemment quelque chose de défectueux.", code: "T2784" },
    { question: "Je me sentirais coupable après avoir perdu mon sang-froid et menacé quelqu'un.", code: "D115" },
    { question: "J'aimerais être pilote de course.", code: "Q120" },
    { question: "J'aimerais être une personne socialement puissante.", code: "S23" },
    { question: "J'aimerais avoir plus de pouvoir que les autres.", code: "Q165" },
    { question: "J'aimerais vivre un moment dans un autre pays.", code: "X158" },
    { question: "J'aimerais essayer le saut à l'élastique.", code: "R77" },
    { question: "J'adorerais être une célébrité.", code: "T2790" },
    { question: "J'adorerais être dans une émission de téléréalité.", code: "T2791" },
    { question: "J'adorerais explorer des endroits étranges.", code: "R71" },
    { question: "J'adorerais jouer devant un public.", code: "T2794" },
    { question: "J'adorerais partir en voyage sans itinéraire ni horaire planifié.", code: "R22" },
    { question: "Je ferais un bon acteur.", code: "P444" },
    { question: "Je ferais un bon comédien de cabaret.", code: "R26" },
    { question: "Je préférerais avoir des amis plutôt que des partenaires romantiques.", code: "T2798" },
    { question: "Je n'accepterais jamais l'aide sociale.", code: "E161" },
    { question: "Je ne serais jamais décrit comme arrogant.", code: "V321" },
    { question: "Je ne tricherais jamais sur mes impôts.", code: "X136" },
    { question: "Je ne ferais jamais de deltaplane ou de saut à l'élastique.", code: "X250" },
    { question: "Je ne descendrais jamais une rivière en canoë dans des rapides.", code: "Q136" },
    { question: "Je ne m'engagerais jamais dans des relations extraconjugales.", code: "Q102" },
    { question: "Je ne ferais jamais un investissement à haut risque.", code: "E71" },
    { question: "Je ne prendrais jamais ce qui ne m'appartient pas.", code: "P367" },
    { question: "Je ne serais pas un bon comédien.", code: "P485" },
    { question: "Je ne serais pas très bouleversé de voir un animal souffrir.", code: "D12" },
    { question: "Je n'apprécierais pas un travail avec beaucoup d'interactions sociales.", code: "D101" },
    { question: "Je n'aimerais pas être une célébrité célèbre.", code: "Q226" },
    { question: "Je n'aimerais pas danser rapidement.", code: "D8" },
    { question: "Je ne me sentirais pas coupable de blesser les sentiments de quelqu'un que je n'aime pas.", code: "D28" },
    { question: "Je ne serais pas très inquiet si un ami se plaignait d'un mal de tête particulièrement intense.", code: "D80" },
    { question: "Je ne regretterais pas d'avoir profité de quelqu'un impulsivement.", code: "D86" },
    { question: "J'obtiendrais des informations spécifiques sur un produit avant de faire un gros achat.", code: "M15" },
    { question: "Je préférerais être dans un ouragan ou un tremblement de terre que de passer la journée à déplacer des briques lourdes.", code: "T2818" },
    { question: "Je préférerais regarder une émission de télévision ennuyeuse plutôt que d'être dans un magasin pendant un vol à main armée.", code: "T2819" },
    { question: "Je préférerais vivre dans un monde imaginaire plutôt que dans le monde réel.", code: "T2820" },
    { question: "Je prétendrais avoir des problèmes personnels pour obtenir de la pitié ou de l'attention.", code: "T2823" },
    { question: "Je préférerais éviter d'utiliser des biens manufacturés.", code: "P381" },
    { question: "Je préférerais être seul que mal accompagné.", code: "M69" },
    { question: "Je préférerais acheter quelque chose dont j'ai besoin plutôt que de l'emprunter à quelqu'un d'autre.", code: "M13" },
    { question: "Je préférerais donner que recevoir.", code: "H121" },
    { question: "Je préférerais m'aider moi-même plutôt que les autres.", code: "T2826" },
    { question: "Je préférerais dépenser de l'argent plutôt que de l'économiser.", code: "Q116" },
    { question: "Je ne ferais pas de mal à une mouche.", code: "H142" },
    { question: "Crier sur des objets inanimés.", code: "E108" },
    { question: "Crier sur les autres avec peu de provocation.", code: "E118" },
    { question: "Crier sur les gens.", code: "H809" }
];

export default DjangoQuestions;